
import config.config;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hiro
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form landingForm
     */
    public Register() {
        initComponents();
        passwordfield1.setEchoChar((char) 0); 
        passwordfield1.setText("Password");
        passwordfield1.setForeground(new java.awt.Color(153, 153, 153));
        
        passwordfield2.setEchoChar((char) 0); 
        passwordfield2.setText("Confirm Password");
        passwordfield2.setForeground(new java.awt.Color(153, 153, 153));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        upPanel = new javax.swing.JPanel();
        BlockPane = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        BlockPane2 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        BlockPane3 = new javax.swing.JPanel();
        Register = new javax.swing.JLabel();
        downPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        remail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordfield1 = new javax.swing.JPasswordField();
        passwordfield2 = new javax.swing.JPasswordField();
        BG = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 0, 51));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upPanel.setBackground(new java.awt.Color(204, 0, 51));
        upPanel.setForeground(new java.awt.Color(255, 255, 255));
        upPanel.setLayout(null);

        BlockPane.setBackground(new java.awt.Color(204, 0, 51));
        BlockPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlockPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BlockPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BlockPaneMouseExited(evt);
            }
        });

        Home.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");

        javax.swing.GroupLayout BlockPaneLayout = new javax.swing.GroupLayout(BlockPane);
        BlockPane.setLayout(BlockPaneLayout);
        BlockPaneLayout.setHorizontalGroup(
            BlockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Home)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        BlockPaneLayout.setVerticalGroup(
            BlockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upPanel.add(BlockPane);
        BlockPane.setBounds(190, 0, 70, 30);

        BlockPane2.setBackground(new java.awt.Color(204, 0, 51));
        BlockPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlockPane2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BlockPane2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BlockPane2MouseExited(evt);
            }
        });

        Login.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("LOGIN");

        javax.swing.GroupLayout BlockPane2Layout = new javax.swing.GroupLayout(BlockPane2);
        BlockPane2.setLayout(BlockPane2Layout);
        BlockPane2Layout.setHorizontalGroup(
            BlockPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPane2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Login)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        BlockPane2Layout.setVerticalGroup(
            BlockPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upPanel.add(BlockPane2);
        BlockPane2.setBounds(260, 0, 70, 30);

        BlockPane3.setBackground(new java.awt.Color(204, 0, 51));
        BlockPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BlockPane3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BlockPane3MouseExited(evt);
            }
        });

        Register.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register.setText("REGISTER");
        Register.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout BlockPane3Layout = new javax.swing.GroupLayout(BlockPane3);
        BlockPane3.setLayout(BlockPane3Layout);
        BlockPane3Layout.setHorizontalGroup(
            BlockPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPane3Layout.createSequentialGroup()
                .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        BlockPane3Layout.setVerticalGroup(
            BlockPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlockPane3Layout.createSequentialGroup()
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        upPanel.add(BlockPane3);
        BlockPane3.setBounds(330, 0, 70, 30);

        jLayeredPane1.add(upPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        downPanel.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout downPanelLayout = new javax.swing.GroupLayout(downPanel);
        downPanel.setLayout(downPanelLayout);
        downPanelLayout.setHorizontalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        downPanelLayout.setVerticalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLayeredPane1.add(downPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 600, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("JOIN US TODAY");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("CREATE YOUR NEW ACCOUNT");

        fname.setForeground(new java.awt.Color(153, 153, 153));
        fname.setText("Full Name");
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ALREADY HAVE AN ACCOUNT?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        remail.setForeground(new java.awt.Color(153, 153, 153));
        remail.setText("Email");
        remail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                remailFocusLost(evt);
            }
        });
        remail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remailActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ICON RED.png"))); // NOI18N

        passwordfield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfield1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfield1FocusLost(evt);
            }
        });
        passwordfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfield1ActionPerformed(evt);
            }
        });

        passwordfield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfield2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfield2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordfield1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fname)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(passwordfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(remail, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addGap(20, 20, 20))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 360, 250));

        BG.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jLayeredPane1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 540, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BlockPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPaneMouseEntered
        BlockPane.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_BlockPaneMouseEntered

    private void BlockPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPaneMouseExited
        BlockPane.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_BlockPaneMouseExited

    private void BlockPane3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane3MouseEntered
        BlockPane3.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_BlockPane3MouseEntered

    private void BlockPane3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane3MouseExited
        BlockPane3.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_BlockPane3MouseExited

    private void BlockPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane2MouseEntered
        BlockPane2.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_BlockPane2MouseEntered

    private void BlockPane2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane2MouseExited
        BlockPane2.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_BlockPane2MouseExited

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void BlockPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPaneMouseClicked
        landingForm home = new landingForm();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BlockPaneMouseClicked

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        if (fname.getText().equals("Full Name")) {
        fname.setText("");
        fname.setForeground(new java.awt.Color(0, 0, 0)); // Change text to black
    }
    }//GEN-LAST:event_fnameFocusGained

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        if (fname.getText().isEmpty()) {
        fname.setForeground(new java.awt.Color(153, 153, 153)); // Change back to gray
        fname.setText("Full Name");
    }
    }//GEN-LAST:event_fnameFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Create an instance of your config class
    config conf = new config();

    // 2. Define the SQL (Assuming your table is named 'users' and columns are 'username', 'password')
    String sql = "INSERT INTO tbl_accounts (full_name, email, password, type, status) VALUES (?, ?, ?, ?, ?)";

    // 3. Get values from your text fields (Update these names to match your variables!)
    String name = fname.getText(); 
    String user = remail.getText(); 
    String pass = new String(passwordfield1.getPassword());
    String confirmPass = new String(passwordfield2.getPassword());

   // 2. VALIDATION: Check for empty fields or placeholder text
            if (name.isEmpty() || name.equals("Full Name") || 
                user.isEmpty() || user.equals("Email") || 
                pass.isEmpty() || pass.equals("Password") || 
                confirmPass.isEmpty() || confirmPass.equals("Confirm Password")) {

                javax.swing.JOptionPane.showMessageDialog(null, "All fields are required!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return; // Stop the code here
            }

    // 3. VALIDATION: Check if passwords match
            if (!pass.equals(confirmPass)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Passwords do not match!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                passwordfield1.setText(""); // Clears bastahaha
                passwordfield2.setText(""); // Clears confirm pass
                return; // Stop the code here
            }
    
    String checkEmailSql = "SELECT * FROM tbl_accounts WHERE email = ?";

        try {
            java.sql.ResultSet rs = conf.getData(checkEmailSql, user);

            if (rs != null && rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Email is already registered!", "Duplicate Entry", javax.swing.JOptionPane.WARNING_MESSAGE);

                // Optional: clear only the email field and focus it
                remail.setText("");
                passwordfield1.setText(""); // Clears bastahaha
                passwordfield2.setText(""); // Clears confirm pass
                remail.requestFocus();

                // Close connection before returning
                rs.getStatement().getConnection().close();
                return; 
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Validation Error: " + e.getMessage());
        }
    
    String hashedPassword = config.hashPassword(pass); 
    // 4. Use your addRecord method to push the data
    conf.addRecord(sql, name, user, hashedPassword, "Staff", "Pending");

    javax.swing.JOptionPane.showMessageDialog(null, "Successfully Registered!");
    
        fname.setText("");            // Clears Full Name
        remail.setText("");           // Clears Email
        passwordfield1.setText(""); // Clears bastahaha
        passwordfield2.setText("");// Clears Password
        fname.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setBackground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setBackground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_jLabel3MouseExited

    private void remailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remailFocusGained
        if (remail.getText().equals("Email")) {
        remail.setText("");
        remail.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_remailFocusGained
    }
    private void remailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remailFocusLost
        if (remail.getText().isEmpty()) {
        remail.setForeground(new java.awt.Color(153, 153, 153)); // Change back to gray
        remail.setText("Email");
    }//GEN-LAST:event_remailFocusLost
    }
    private void remailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remailActionPerformed

    private void BlockPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane2MouseClicked
        Login loginWindow = new Login();
        loginWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BlockPane2MouseClicked

    private void passwordfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfield1ActionPerformed

    private void passwordfield1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield1FocusGained
        // String.valueOf(passwordfield.getPassword()) is the safe way to check the text
        if (String.valueOf(passwordfield1.getPassword()).equals("Password")) {
            passwordfield1.setText("");
            passwordfield1.setEchoChar('•'); // Switch to dots
            passwordfield1.setForeground(new java.awt.Color(0, 0, 0)); 
    }
    }//GEN-LAST:event_passwordfield1FocusGained

    private void passwordfield1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield1FocusLost
        if (passwordfield1.getPassword().length == 0) {
        passwordfield1.setEchoChar((char) 0); // Remove dots so we can see the word
        passwordfield1.setText("Password");
        passwordfield1.setForeground(new java.awt.Color(153, 153, 153));
    }
    }//GEN-LAST:event_passwordfield1FocusLost

    private void passwordfield2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield2FocusGained
        // String.valueOf(passwordfield.getPassword()) is the safe way to check the text
        if (String.valueOf(passwordfield2.getPassword()).equals("Confirm Password")) {
            passwordfield2.setText("");
            passwordfield2.setEchoChar('•'); // Switch to dots
            passwordfield2.setForeground(new java.awt.Color(0, 0, 0)); 
    }
    }//GEN-LAST:event_passwordfield2FocusGained

    private void passwordfield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield2FocusLost
        if (passwordfield2.getPassword().length == 0) {
        passwordfield2.setEchoChar((char) 0); // Remove dots so we can see the word
        passwordfield2.setText("Confirm Password");
        passwordfield2.setForeground(new java.awt.Color(153, 153, 153));
    }
    }//GEN-LAST:event_passwordfield2FocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Login loginWindow = new Login();
        loginWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BlockPane;
    private javax.swing.JPanel BlockPane2;
    private javax.swing.JPanel BlockPane3;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Register;
    private javax.swing.JPanel downPanel;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passwordfield1;
    private javax.swing.JPasswordField passwordfield2;
    private javax.swing.JTextField remail;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
