package pages;


import pages.Register;
import Login.Login;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hiro
 */
public class landingForm extends javax.swing.JFrame {

    /**
     * Creates new form landingForm
     */
    public landingForm() {
        initComponents();
        upPanel.getParent().setComponentZOrder(upPanel, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        SubText = new javax.swing.JLabel();
        upPanel = new javax.swing.JPanel();
        BlockPane = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        BlockPane2 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        BlockPane3 = new javax.swing.JPanel();
        Register = new javax.swing.JLabel();
        downPanel = new javax.swing.JPanel();
        Header1 = new javax.swing.JLabel();
        BG = new javax.swing.JPanel();
        Grow1 = new javax.swing.JPanel();
        learnMore = new javax.swing.JLabel();
        Grow = new javax.swing.JPanel();
        SubText3 = new javax.swing.JLabel();
        Connect = new javax.swing.JPanel();
        SubText1 = new javax.swing.JLabel();
        Innovate = new javax.swing.JPanel();
        SubText2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 0, 51));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubText.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        SubText.setForeground(new java.awt.Color(255, 255, 255));
        SubText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubText.setText("Unlock your potential with our platform");
        SubText.setToolTipText("");
        jLayeredPane1.add(SubText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 300, 50));

        upPanel.setBackground(new java.awt.Color(204, 0, 51));
        upPanel.setForeground(new java.awt.Color(255, 255, 255));
        upPanel.setLayout(null);

        BlockPane.setBackground(new java.awt.Color(204, 0, 51));
        BlockPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BlockPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BlockPaneMouseExited(evt);
            }
        });

        Home.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("HOME");

        javax.swing.GroupLayout BlockPaneLayout = new javax.swing.GroupLayout(BlockPane);
        BlockPane.setLayout(BlockPaneLayout);
        BlockPaneLayout.setHorizontalGroup(
            BlockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Home)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        BlockPaneLayout.setVerticalGroup(
            BlockPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upPanel.add(BlockPane);
        BlockPane.setBounds(190, 0, 70, 30);

        BlockPane2.setBackground(new java.awt.Color(204, 0, 51));
        BlockPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlockPane2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BlockPane2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BlockPane2MouseExited(evt);
            }
        });

        Login.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("LOGIN");

        javax.swing.GroupLayout BlockPane2Layout = new javax.swing.GroupLayout(BlockPane2);
        BlockPane2.setLayout(BlockPane2Layout);
        BlockPane2Layout.setHorizontalGroup(
            BlockPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPane2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Login)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        BlockPane2Layout.setVerticalGroup(
            BlockPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upPanel.add(BlockPane2);
        BlockPane2.setBounds(260, 0, 70, 30);

        BlockPane3.setBackground(new java.awt.Color(204, 0, 51));
        BlockPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlockPane3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BlockPane3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BlockPane3MouseExited(evt);
            }
        });

        Register.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register.setText("REGISTER");
        Register.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout BlockPane3Layout = new javax.swing.GroupLayout(BlockPane3);
        BlockPane3.setLayout(BlockPane3Layout);
        BlockPane3Layout.setHorizontalGroup(
            BlockPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlockPane3Layout.createSequentialGroup()
                .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        BlockPane3Layout.setVerticalGroup(
            BlockPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlockPane3Layout.createSequentialGroup()
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        upPanel.add(BlockPane3);
        BlockPane3.setBounds(330, 0, 70, 30);

        jLayeredPane1.add(upPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        downPanel.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout downPanelLayout = new javax.swing.GroupLayout(downPanel);
        downPanel.setLayout(downPanelLayout);
        downPanelLayout.setHorizontalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        downPanelLayout.setVerticalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLayeredPane1.add(downPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 600, 30));

        Header1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        Header1.setForeground(new java.awt.Color(255, 255, 255));
        Header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header1.setText("IGNITE YOUR PASSION");
        Header1.setToolTipText("");
        jLayeredPane1.add(Header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 470, 80));

        BG.setBackground(new java.awt.Color(153, 0, 51));

        Grow1.setBackground(new java.awt.Color(204, 0, 51));
        Grow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Grow1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Grow1MouseExited(evt);
            }
        });

        learnMore.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        learnMore.setForeground(new java.awt.Color(255, 255, 255));
        learnMore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        learnMore.setText("Learn More");
        learnMore.setToolTipText("");

        javax.swing.GroupLayout Grow1Layout = new javax.swing.GroupLayout(Grow1);
        Grow1.setLayout(Grow1Layout);
        Grow1Layout.setHorizontalGroup(
            Grow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Grow1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(learnMore, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Grow1Layout.setVerticalGroup(
            Grow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(learnMore)
        );

        Grow.setBackground(new java.awt.Color(204, 0, 51));
        Grow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GrowMouseExited(evt);
            }
        });

        SubText3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        SubText3.setForeground(new java.awt.Color(255, 255, 255));
        SubText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubText3.setText("GROW");
        SubText3.setToolTipText("");

        javax.swing.GroupLayout GrowLayout = new javax.swing.GroupLayout(Grow);
        Grow.setLayout(GrowLayout);
        GrowLayout.setHorizontalGroup(
            GrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrowLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(SubText3)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        GrowLayout.setVerticalGroup(
            GrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrowLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(SubText3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Connect.setBackground(new java.awt.Color(204, 0, 51));
        Connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConnectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConnectMouseExited(evt);
            }
        });

        SubText1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        SubText1.setForeground(new java.awt.Color(255, 255, 255));
        SubText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubText1.setText("CONNECT");
        SubText1.setToolTipText("");

        javax.swing.GroupLayout ConnectLayout = new javax.swing.GroupLayout(Connect);
        Connect.setLayout(ConnectLayout);
        ConnectLayout.setHorizontalGroup(
            ConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnectLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(SubText1)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ConnectLayout.setVerticalGroup(
            ConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnectLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(SubText1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Innovate.setBackground(new java.awt.Color(204, 0, 51));
        Innovate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InnovateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InnovateMouseExited(evt);
            }
        });

        SubText2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        SubText2.setForeground(new java.awt.Color(255, 255, 255));
        SubText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubText2.setText("INNOVATE");
        SubText2.setToolTipText("");

        javax.swing.GroupLayout InnovateLayout = new javax.swing.GroupLayout(Innovate);
        Innovate.setLayout(InnovateLayout);
        InnovateLayout.setHorizontalGroup(
            InnovateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InnovateLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(SubText2)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        InnovateLayout.setVerticalGroup(
            InnovateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InnovateLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(SubText2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Innovate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(Grow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(Connect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(Grow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BGLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(Grow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Connect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Innovate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jLayeredPane1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 540, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BlockPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPaneMouseEntered
        BlockPane.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_BlockPaneMouseEntered

    private void BlockPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPaneMouseExited
        BlockPane.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_BlockPaneMouseExited

    private void BlockPane3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane3MouseEntered
        BlockPane3.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_BlockPane3MouseEntered

    private void BlockPane3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane3MouseExited
        BlockPane3.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_BlockPane3MouseExited

    private void BlockPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane2MouseEntered
        BlockPane2.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_BlockPane2MouseEntered

    private void BlockPane2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane2MouseExited
        BlockPane2.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_BlockPane2MouseExited

    private void InnovateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnovateMouseEntered
        Innovate.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_InnovateMouseEntered

    private void InnovateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnovateMouseExited
        Innovate.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_InnovateMouseExited

    private void GrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrowMouseEntered
        Grow.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_GrowMouseEntered

    private void GrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrowMouseExited
        Grow.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_GrowMouseExited

    private void ConnectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectMouseEntered
        Connect.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_ConnectMouseEntered

    private void ConnectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectMouseExited
        Connect.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_ConnectMouseExited

    private void BlockPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane2MouseClicked
            Login loginWindow = new Login(); // Create the Login window
            loginWindow.setVisible(true);    // Show the Login window
            this.dispose();
    }//GEN-LAST:event_BlockPane2MouseClicked

    private void BlockPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlockPane3MouseClicked
        Register registerWindow = new Register();
        registerWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BlockPane3MouseClicked

    private void Grow1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grow1MouseEntered
        Grow1.setBackground(new java.awt.Color(255, 102, 102));
    }//GEN-LAST:event_Grow1MouseEntered

    private void Grow1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grow1MouseExited
        Grow1.setBackground(new java.awt.Color(204, 0, 51));
    }//GEN-LAST:event_Grow1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel BlockPane;
    private javax.swing.JPanel BlockPane2;
    private javax.swing.JPanel BlockPane3;
    private javax.swing.JPanel Connect;
    private javax.swing.JPanel Grow;
    private javax.swing.JPanel Grow1;
    private javax.swing.JLabel Header1;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel Innovate;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel SubText;
    private javax.swing.JLabel SubText1;
    private javax.swing.JLabel SubText2;
    private javax.swing.JLabel SubText3;
    private javax.swing.JPanel downPanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel learnMore;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
