package Users;

import Login.Login;
import config.config;
import javax.swing.JOptionPane;
import Users.UserView;



public class addUser extends javax.swing.JFrame {

    public String action =""; 
    
    public int userID;
    
    public addUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upPanel = new javax.swing.JPanel();
        BG = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        remail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordfield1 = new javax.swing.JPasswordField();
        passwordfield2 = new javax.swing.JPasswordField();
        Type = new javax.swing.JComboBox<>();
        Status = new javax.swing.JComboBox<>();
        downPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        upPanel.setBackground(new java.awt.Color(204, 0, 51));
        upPanel.setForeground(new java.awt.Color(255, 255, 255));
        upPanel.setLayout(null);

        BG.setBackground(new java.awt.Color(153, 0, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel1.setText("Add User");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Create the Account");

        fname.setForeground(new java.awt.Color(153, 153, 153));
        fname.setText("Full Name");
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        jButton1.setText("Add User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        remail.setForeground(new java.awt.Color(153, 153, 153));
        remail.setText("Email");
        remail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                remailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                remailFocusLost(evt);
            }
        });
        remail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remailActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ICON RED.png"))); // NOI18N

        passwordfield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfield1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfield1FocusLost(evt);
            }
        });
        passwordfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfield1ActionPerformed(evt);
            }
        });

        passwordfield2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfield2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfield2FocusLost(evt);
            }
        });

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff", "Donor" }));
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Pending" }));
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fname)
                            .addComponent(passwordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remail)
                            .addComponent(passwordfield2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(Type, 0, 151, Short.MAX_VALUE)
                            .addComponent(Status, 0, 151, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        downPanel.setBackground(new java.awt.Color(204, 0, 51));

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout downPanelLayout = new javax.swing.GroupLayout(downPanel);
        downPanel.setLayout(downPanelLayout);
        downPanelLayout.setHorizontalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        downPanelLayout.setVerticalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downPanelLayout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(upPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(downPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        if (fname.getText().equals("Full Name")) {
            fname.setText("");
            fname.setForeground(new java.awt.Color(0, 0, 0)); // Change text to black
        }
    }//GEN-LAST:event_fnameFocusGained

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        if (fname.getText().isEmpty()) {
            fname.setForeground(new java.awt.Color(153, 153, 153)); // Change back to gray
            fname.setText("Full Name");
        }
    }//GEN-LAST:event_fnameFocusLost

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        config con = new config();
        
        if (action == null || action.isEmpty()) {
        action = "Add";
        }

            // 1. Get the text from your fields
            String fullName = fname.getText();
            String email = remail.getText();
            String password = String.valueOf(passwordfield1.getPassword());
            String confirmPass = String.valueOf(passwordfield2.getPassword());
            String accountType = Type.getSelectedItem().toString(); 

                // 3. Validation (Added check for the dropdown if needed)
                if(fullName.equals("Full Name") || email.equals("Email") || password.equals("Password")) {
                    JOptionPane.showMessageDialog(null, "Please fill in all fields!");
                } else if (!password.equals(confirmPass)) {
                    JOptionPane.showMessageDialog(null, "Passwords do not match!");
                } else {
                // 2. LOGIC SWITCH: ADD vs UPDATE
                        if (action.equals("Add")) {
                            // Validation for NEW users (Password is required)
                            if (password.isEmpty() || password.equals("Password")) {
                                JOptionPane.showMessageDialog(null, "Password is required for new users!");
                            } else if (!password.equals(confirmPass)) {
                                JOptionPane.showMessageDialog(null, "Passwords do not match!");
                            } else {
                                String sql = "INSERT INTO tbl_accounts (full_name, email, password, type, status) VALUES (?, ?, ?, ?, ?)";
                                con.addRecord(sql, fullName, email, config.hashPassword(password), accountType, "Pending");
                                closeAndReturn();
                            }

                        } else if (action.equals("Update")) {
                            // 1. Validation (Usually you don't require password change during update)
                                if (fname.getText().isEmpty() || remail.getText().isEmpty()) {
                                    JOptionPane.showMessageDialog(null, "All fields are required!");
                                } else {
                                    // 2. The SQL Update Query
                                    String sql = "UPDATE tbl_accounts SET full_name = ?, email = ?, type = ?, status = ? WHERE u_id = ?";

                                    // 3. Execute using your config class
                                    con.addRecord(sql, fname.getText(), remail.getText(), Type.getSelectedItem().toString(), Status.getSelectedItem().toString(), userID);

                                    JOptionPane.showMessageDialog(null, "User Updated Successfully!");
                                    closeAndReturn();
                        }
                    }
                }
    }//GEN-LAST:event_jButton1ActionPerformed
        private void closeAndReturn() {
                // 3. Assume success and navigate back
                JOptionPane.showMessageDialog(null, "Action Processed!");
                this.dispose();
                UserView uv = new UserView();
                uv.setVisible(true);
}
    private void remailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remailFocusGained
        if (remail.getText().equals("Email")) {
            remail.setText("");
            remail.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_remailFocusGained

    private void remailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_remailFocusLost
        if (remail.getText().isEmpty()) {
            remail.setForeground(new java.awt.Color(153, 153, 153)); // Change back to gray
            remail.setText("Email");
        }
    }//GEN-LAST:event_remailFocusLost

    private void remailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remailActionPerformed

    private void passwordfield1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield1FocusGained
        // String.valueOf(passwordfield.getPassword()) is the safe way to check the text
        if (String.valueOf(passwordfield1.getPassword()).equals("Password")) {
            passwordfield1.setText("");
            passwordfield1.setEchoChar('•'); // Switch to dots
            passwordfield1.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_passwordfield1FocusGained

    private void passwordfield1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield1FocusLost
        if (passwordfield1.getPassword().length == 0) {
            passwordfield1.setEchoChar((char) 0); // Remove dots so we can see the word
            passwordfield1.setText("Password");
            passwordfield1.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_passwordfield1FocusLost

    private void passwordfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfield1ActionPerformed

    private void passwordfield2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield2FocusGained
        // String.valueOf(passwordfield.getPassword()) is the safe way to check the text
        if (String.valueOf(passwordfield2.getPassword()).equals("Confirm Password")) {
            passwordfield2.setText("");
            passwordfield2.setEchoChar('•'); // Switch to dots
            passwordfield2.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_passwordfield2FocusGained

    private void passwordfield2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfield2FocusLost
        if (passwordfield2.getPassword().length == 0) {
            passwordfield2.setEchoChar((char) 0); // Remove dots so we can see the word
            passwordfield2.setText("Confirm Password");
            passwordfield2.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_passwordfield2FocusLost

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
            UserView uv = new UserView();
            uv.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (config.Session.id == 0){
                    new Login().setVisible(true);
                } else {
                new addUser().setVisible(true);
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    public javax.swing.JComboBox<String> Status;
    public javax.swing.JComboBox<String> Type;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel downPanel;
    public javax.swing.JTextField fname;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordfield1;
    private javax.swing.JPasswordField passwordfield2;
    public javax.swing.JTextField remail;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
